version: "3.7"
services:
  app:
    build: .
    container_name: app
    entrypoint: /usr/local/bin/docker-php-entrypoint
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    tty: true